services:
  flask:
    build: ./flask
    container_name: flask-app

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80" # Maping port 80 to port 80 on the container
    depends_on:
      - flask